feature(status): refactor
devsoc-unsw/devsoc-website pull request #6
Opened 2024-02-06 09:57 UTC by 3bobchen

2024-02-07 03:10 UTC, francojreyes requested changes

2024-02-07 03:10 UTC, francojreyes commented on app/(pages)/status/page.tsx
> +                                marginBottom: "2rem"
Is this what's causing there to be a large gap below Chaos on the page? Maybe rather than giving everything a bottom margin, we wrap this map in a Stack (flexbox) with spacing (a prop of Stack).

2024-02-07 03:10 UTC, francojreyes commented on app/(pages)/status/status.json
Do we need this file anymore?

2024-02-07 03:10 UTC, francojreyes commented on data.ts
Why do you have 4 space formatting for JS I feel like that's not standard

2024-02-07 03:10 UTC, francojreyes commented on app/(pages)/status/page.tsx
> +                                    <Typography sx={{fontWeight: 700}}>
This is another place where it would be cleaner to use the system prop `fontWeight={700}` over `sx`

2024-02-07 03:10 UTC, francojreyes commented on app/(pages)/status/page.tsx
> +function renderProjectLogo(name: string) {
Is there a need for this function? `projectsData` that you're mapping over already contains image sources and names.

I think it isn't great that the image sources in there are strings rather than imports, but it would be a lot of imports so I didn't bother.

2024-02-07 03:10 UTC, francojreyes commented on components/ProjectCard.tsx
> +  status?: "Operational" | "Unavailable"
Do you think it would be better to make this a boolean and call it `operational` or something similar? You don't actually use these values for rendering, it gets turned into a boolean.

2024-02-07 03:10 UTC, francojreyes commented on app/(pages)/status/page.tsx
> +interface StatusBubbleProps {
This should probably be with `StatusBubble`

2024-02-07 03:10 UTC, francojreyes commented on app/(pages)/status/page.tsx
> +            <Box sx={{
I feel like this would be cleaner as a bunch of ternaries e.g. `color={status ? "white" :" black"}` etc.

Also again, try use the [system props](https://mui.com/system/properties/).

2024-02-07 03:20 UTC, francojreyes commented
I can't comment on the file since you didn't edit it, but there's a TODO in `app/layout.tsx` about automatically displaying the banner if at least one/some number of projects is unavailable - could you implement this too?

2024-02-09 11:28 UTC, 3bobchen commented on components/ProjectCard.tsx
> +  status?: "Operational" | "Unavailable"
I think it's better to preserve flexibility at this stage since we may want other statuses. I feel like I've seen "Partial Outage" or "Scheduled Maintenance" etc which provide an inbetween to simply working and not. Lmk your thoughts.

2024-02-09 11:29 UTC, 3bobchen commented on app/(pages)/status/page.tsx
> +interface StatusBubbleProps {
Wait but the component is StatusBubble, wouldnt naming the props type for it the same name clash/be confusing?

2024-02-09 11:36 UTC, francojreyes commented on app/(pages)/status/page.tsx
> +interface StatusBubbleProps {
I mean this type should be moved to be above `StatusBubble`

2024-02-09 11:38 UTC, francojreyes commented on data.ts
Yis 2 pls, I personally think 2 is a lot nicer since JSX is designed to be very nested, so large indents makes things a bit less coherent.

2024-02-09 11:38 UTC, francojreyes commented on components/ProjectCard.tsx
> +  status?: "Operational" | "Unavailable"
Fair point, can leave it as is then.

2024-02-09 11:51 UTC, 3bobchen commented on app/(pages)/status/page.tsx
> +                                marginBottom: "2rem"
idt Stack works on server side rendered components and i cant make this page client side rendered easily. I'll look tmr.

2024-02-09 11:56 UTC, francojreyes commented on app/(pages)/status/page.tsx
> +                                marginBottom: "2rem"
Stacks should work fine for server components, the other pages use them plenty and are all server side (the homepage is not server side though). They're just thin CSS abstractions so I don't see why there'd be an issue.

2024-02-10 06:03 UTC, 3bobchen commented on app/(pages)/status/page.tsx
> +interface StatusBubbleProps {
god i was so tired i didnt read the with

2024-02-10 08:03 UTC, francojreyes requested changes

2024-02-10 08:03 UTC, francojreyes commented on app/layout.tsx
> +function checkForIssues(data: Omit<ProjectCardProps, 'trainee'>[]): boolean {
Take a look at the [.some()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) function of JS arrays. Essentially does what this function does, and would allow for a lot of inlining (i.e. can put this condition straight into the JSX probably).

2024-02-10 08:03 UTC, francojreyes commented on data.ts
This file looks like it's been 4 space formatted?

2024-02-10 12:33 UTC, 3bobchen commented on app/layout.tsx
> +                                         }: {
i blame webstorm :p

2024-02-10 12:43 UTC, 3bobchen commented on app/layout.tsx
> +function checkForIssues(data: Omit<ProjectCardProps, 'trainee'>[]): boolean {
so cooool

2024-02-10 13:36 UTC, francojreyes commented on app/layout.tsx
> +  const issue = (item: Omit<ProjectCardProps, 'trainee'>) => item.status === "Unavailable"
Not sure why this needs to be a variable. If you inline it within the `some()` you no longer need the type hint so it's a bit cleaner.

Honestly, you could even put it directly into the JSX e.g.
```
projectData.some(proj => proj.status === "Undefined") &&
...
```

2024-02-10 23:46 UTC, francojreyes approved these changes

2024-02-10 23:46 UTC, merged